---

- name: Install the EPEL repository
  ansible.builtin.package:
    name: epel-release

- name: Install Certbot and Cloudflare Plugin
  ansible.builtin.package:
    name:
      - certbot
      - python3-certbot-dns-cloudflare

- name: Configure certbot hooks
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/certbot
    regexp: '^{{ item.type }}_HOOK='
    line: '{{ item.type }}_HOOK="{{ item.hook }}"'
  loop:
    - type: PRE
      hook: '{{ certbot_cloudflare_pre_hook }}'
    - type: POST
      hook: '{{ certbot_cloudflare_post_hook }}'

- name: Configure Cloudflare API token
  ansible.builtin.copy:
    content: dns_cloudflare_api_token = {{ certbot_cloudflare_api_token }}
    dest: /etc/cloudflare.ini
    owner: root
    group: root
    mode: '0600'

- name: Request initial certificate
  ansible.builtin.command:
    cmd: >-
      certbot certonly
      --noninteractive
      --agree-tos
      -m {{ certbot_cloudflare_email }}
      --dns-cloudflare
      --dns-cloudflare-credentials /etc/cloudflare.ini
      -d {{ ' -d '.join(certbot_cloudflare_domains) }}
    creates: >-
      /etc/letsencrypt/live/{{ certbot_cloudflare_domains[0] }}/fullchain.pem

- name: Enable renewal timer
  ansible.builtin.systemd:
    name: certbot-renew.timer
    state: started
    enabled: true
